INSERT INTO Exercise_Goal (goal, exercise)
VALUES('muscleGrowth','Deadlift'),
('maxStrength','Deadlift'),
('muscleGrowth','Hip thrust'),
('maxStrength','Hip thrust'),
('xSkiing','Kickbacks body weight'),
('weightLoss','Kickbacks body weight'),
('muscleGrowth','Pull down'),
('maxStrength','Pull down'),
('xSkiing','Pull down'),
('weightLoss','Hyperextensions'),
('xSkiing','Hyperextensions'),
('maxStrength','Hyperextensions'),
('muscleGrowth','Pullover'),
('xSkiing','Pullover'),
('muscleGrowth','Cable row'),
('maxStrength','Cable row'),
('weightLoss','Band row'),
('maxStrength','Band row'),
('muscleGrowth','Band row'),
('muscleGrowth','Straight arm pull down'),
('xSkiing','Straight arm pull down'),
('muscleGrowth','Shoulder press'),
('maxStrength','Shoulder press'),
('muscleGrowth','Lateral raise'),
('weightLoss','Lateral raise body weight'),
('muscleGrowth','Lateral raise body weight'),
('maxStrength','Lateral raise body weight'),
('muscleGrowth','Military press'),
('maxStrength','Military press'),
('muscleGrowth','Face pull'),
('xSkiing','Face pull'),
('muscleGrowth','Bench'),
('maxStrength','Bench'),
('muscleGrowth','Push ups body weight'),
('weightLoss','Push ups body weight'),
('xSkiing','Push ups body weight'),
('weightLoss','Knee push ups'),
('xSkiing','Knee push ups'),
('muscleGrowth','Dips body weight'),
('xSkiing','Dips body weight'),
('muscleGrowth','Nordic hamstrings'),
('maxStrength','Nordic hamstrings'),
('xSkiing','Nordic hamstrings'),
('muscleGrowth','Leg curl'),
('maxStrength','Leg curl'),
('weightLoss','Leg curl body weight'),
('xSkiing','Back extension body weight'),
('weightLoss','Back extension body weight'),
('muscleGrowth','Sit-ups'),
('weightLoss','Sit-ups'),
('xSkiing','Sit-ups'),
('xSkiing','Roll out wheel'),
('maxStrength','Roll out wheel'),
('muscleGrowth','Roll out wheel'),
('xSkiing','Plank'),
('xSkiing','Bicycle'),
('weightLoss','Bicycle'),
('xSkiing','Pikes gymBall'),
('maxStrength','Pikes gymBall'),
('muscleGrowth','Pikes gymBall'),
('weightLoss','Leg raise'),
('xSkiing','Leg raise'),
('muscleGrowth','Biceps curl'),
('muscleGrowth','Squat'),
('maxStrength','Squat'),
('weightLoss','KneeLifts'),
('xSkiing','KneeLifts'),
('weightLoss','Step up body weight'),
('xSkiing','Step up body weight'),
('weightLoss','Walking lunges body weight'),
('xSkiing','Walking lunges body weight'),
('maxStrength','Walking lunges body weight'),
('xSkiing','One-leg squat body weight'),
('maxStrength','One-leg squat body weight'),
('weightLoss','Bench dips body weight'),
('xSkiing','Bench dips body weight'),
('muscleGrowth','Triceps push down'),
('xSkiing','Triceps push down'),
('muscleGrowth','JM-press'),
('maxStrength','JM-press');