INSERT INTO Exercise (name, difficulty, defaultKg, description, equipment, muscle, type)
VALUES('Deadlift',7,40.0,'Pull bar up from the ground','bar','glutes','compound'),
('Hip thrust',5,40.0,'thrust','bench','glutes','compound'),
('Kickbacks body weight',3,0.0,'Lean with hands on a wall and kick one leg back','none','glutes','bodyWeight'),
('Pull down',3,20.0,'pull down','pulldownMachine','lats','compound'),
('Hyperextensions',2,0.0,'hyper extend lying facing down','mat','lats','bodyWeight'),
('Pullover',6,10.0,'pull over','bar','lats','isolation'),
('Cable row',4,15.0,'row','cableRow','back','compound'),
('Band row',3,0.0,'row','band','back','compound'),
('Straight arm pull down',4,10.0,'pull bar down','cableMachine','back','isolation'),
('Shoulder press',6,4.0,'press above head','dumbells','shoulders','compound'),
('Lateral raise',2,1.0,'With arms straight, raise dumbells up to each side','dumbells','shoulders','isolation'),
('Lateral raise body weight',1,0.0,'Lateral raise','none','shoulders','bodyWeight'),
('Military press',7,20.0,'Push bar above head','bar','shoulders','compound'),
('Face pull',4,10.0,'Pull cable towards your face','cableMachine','shoulders','isolation'),
('Bench',5,30.0,'Lie on your back on the bench. Lower bar to your chest and push back up','benchPressRack','chest','compound'),
('Push ups body weight',4,0.0,'push up','none','chest','bodyWeight'),
('Knee push ups',3,0.0,'push up','mat','chest','bodyWeight'),
('Dips body weight',5,0.0,'extend arms','dipsBar','chest','bodyWeight'),
('Nordic hamstrings',4,0.0,'hamstring curl','none','hamstrings','bodyWeight'),
('Leg curl',1,15.0,'curl legs','legCurl','hamstrings','isolation'),
('Leg curl body weight',2,0.0,'Lying leg curls','mat','hamstrings','bodyWeight'),
('Back extension body weight',4,0.0,'extend back','backExtension','hamstrings','bodyWeight'),
('Sit-ups',3,0.0,'sit up','none','abs','bodyWeight'),
('Roll out wheel',4,0.0,'roll out','rolloutWheel','abs','isolation'),
('Plank',3,0.0,'plank','mat','abs','bodyWeight'),
('Bicycle',4,0.0,'Cycle with legs lying on your back','mat','abs','bodyWeight'),
('Pikes gymBall',7,0.0,'Pikes with gymBall','gymBall','abs','isolation'),
('Leg raise',3,0.0,'Raise your legs extended lying on your back; isolation','mat','abs','bodyWeight'),
('Biceps curl',2,4.0,'curl','dumbells','biceps','isolation'),
('Squat',7,20.0,'Ass to the grass, bro','rack','quadriceps','compound'),
('KneeLifts',1,0.0,'Lift knee up alternating left and right','none','quadriceps','bodyWeight'),
('Step up body weight',3,0.0,'Step up on the box using alternating legs','stepBox','quadriceps','bodyWeight'),
('Walking lunges body weight',5,0.0,'lunge walking','none','quadriceps','bodyWeight'),
('One-leg squat body weight',7,0.0,'squat to the ground on one leg. Grap pole and squat back up.','pole','quadriceps','bodyWeight'),
('Bench dips body weight',3,0.0,'extend arms','bench','triceps','bodyWeight'),
('Triceps push down',2,12.5,'push down','cableMachine','triceps','isolation'),
('JM-press',6,10.0,'jm-press','bar','triceps','isolation');