INSERT INTO Muscles_In_Exercise (muscle, exercise)
VALUES('glutes','Deadlift'),
('hamstrings','Deadlift'),
('quadriceps','Deadlift'),
('back','Deadlift'),
('glutes','Hip thrust'),
('hamstrings','Hip thrust'),
('glutes','Kickbacks body weight'),
('lats','Pull down'),
('back','Pull down'),
('lats','Hyperextensions'),
('back','Hyperextensions'),
('lats','Pullover'),
('back','Pullover'),
('triceps','Pullover'),
('back','Cable row'),
('lats','Cable row'),
('back','Band row'),
('lats','Band row'),
('back','Straight arm pull down'),
('lats','Straight arm pull down'),
('shoulders','Shoulder press'),
('shoulders','Lateral raise'),
('shoulders','Lateral raise body weight'),
('shoulders','Military press'),
('triceps','Military press'),
('shoulders','Face pull'),
('back','Face pull'),
('chest','Bench'),
('shoulders','Bench'),
('triceps','Bench'),
('chest','Push ups body weight'),
('triceps','Push ups body weight'),
('shoulders','Push ups body weight'),
('chest','Knee push ups'),
('triceps','Knee push ups'),
('shoulders','Knee push ups'),
('chest','Dips body weight'),
('triceps','Dips body weight'),
('shoulders','Dips body weight'),
('hamstrings','Nordic hamstrings'),
('hamstrings','Leg curl'),
('hamstrings','Leg curl body weight'),
('hamstrings','Back extension body weight'),
('glutes','Back extension body weight'),
('abs','Sit-ups'),
('abs','Roll out wheel'),
('abs','Plank'),
('abs','Bicycle'),
('abs','Pikes gymBall'),
('abs','Leg raise'),
('biceps','Biceps curl'),
('quadriceps','Squat'),
('glutes','Squat'),
('hamstrings','Squat'),
('quadriceps','KneeLifts'),
('quadriceps','Step up body weight'),
('glutes','Step up body weight'),
('hamstrings','Step up body weight'),
('quadriceps','Walking lunges body weight'),
('glutes','Walking lunges body weight'),
('hamstrings','Walking lunges body weight'),
('quadriceps','One-leg squat body weight'),
('glutes','One-leg squat body weight'),
('hamstrings','One-leg squat body weight'),
('triceps','Bench dips body weight'),
('chest','Bench dips body weight'),
('shoulders','Bench dips body weight'),
('triceps','Triceps push down'),
('triceps','JM-press');